version: '3.8'

services:
  # The Backend API Service
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: insurance_api
    ports:
      - "8000:8000"
    volumes:
      - ./logs:/app/logs

  # The Frontend UI Service
  ui:
    build:
      context: .
      dockerfile: Dockerfile.ui
    container_name: insurance_ui
    ports:
      - "8501:8501"
    environment:
      - DOCKER_ENV=true   
    depends_on:
      - api